### ISSUE TITLE
Comentar las clases y funciones

### ISSUE THREAD

**Issue by 0mar089** [wiinterrr/Editor-de-fotos#7]

**Comment by wiinterrr** [comment]
animos roc

**Comment by 0mar089** [comment]
Roc tu puedes

**Comment by wiinterrr** [comment]
haz los comentarios en la rama `master-con-comentarios-hechos` asi puedes hacer cambios aunque alguien esté haciendo algo en la rama master y luego ya lo juntaremos

**Comment by wiinterrr** [comment]
ya comenté el menú y puse algo en alguna que otra funcion
